# frontend
apiVersion: app/v1
kind: Deployment
metadata:
  name: appkubernetesponcho
  namespace: cursokubernetesponcho
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appkubernetesponcho
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
  template:
    metadata:
      labels:
        app: appkubernetesponcho
        role: appkubernetesponcho
    spec:
      containers:
        - name: appkubernetesponcho
          image: fernandofar/app:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: appkubernetesponcho

# backend
apiVersion: v1
kind: Service
metadata:
  name: appkubernetesponcho
  namespace: cursokubernetesponcho
  labels:
    app: appkubernetesponcho
spec:
  selector:
    app: appkubernetesponcho
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    role: appkubernetesponcho