apiVersion: v1
kind: Namespace
metadata:
  name: cursokubernetesponcho2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podappponcho
  namespace: cursokubernetesponcho2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podappponcho
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
  template:
    metadata:
      labels:
        app: podappponcho
        role: podappponcho
    spec:
      containers:
        - name: podappponcho
          image: fernandofar/app:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: podappponcho
---
apiVersion: v1
kind: Service
metadata:
  name: podappponcho
  namespace: cursokubernetesponcho2
  labels:
    app: podappponcho
spec:
  selector:
   app: podappponcho
  type: ClusterIP
  ports:
   - name: http
     port: 80
     protocol: TCP
     targetPort: 80
  selector:
    role: podappponcho