apiVersion: v1
kind: Namespace
metadata:
  name: cursokubernetesponcho2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podphpmyadminponcho2
  namespace: cursokubernetesponcho2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podphpmyadminponcho2
  template:
    metadata:
      labels:
        app: podphpmyadminponcho2
    spec:
      containers:
        - name: podphpmyadminponcho2
          image: fernandofar/phpmyadmin:v1
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: serviciomysqlponcho2
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secretomysqlponcho2
                  key: password
          volumeMounts:
            - name: sessions
              mountPath: /sessions
      volumes:
        - name: sessions
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: serviciophpmyadminponcho2
  namespace: cursokubernetesponcho2
spec:
  type: ClusterIP
  selector:
    app: serviciophpmyadminponcho2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

